steps:
- id: Retag
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - -exc
  - | 
    docker pull gcr.io/ubbagent/metering/ubbagent:sha_$COMMIT_SHA
    docker tag gcr.io/ubbagent/metering/ubbagent:sha_$COMMIT_SHA gcr.io/$PROJECT_ID/metering/ubbagent:$TAG_NAME

images:
- gcr.io/$PROJECT_ID/metering/ubbagent:$TAG_NAME
