# Used for building tagged releases.
# It updates the "latest" tag in the corresponding GCR repos
# if the current SemVer is the most recent.
#
# This does not actually build images; it copies candidates
# built in the staging project instead. These images should have
# been built by cloudbuild.yaml, which should be triggered on
# every new commit.

substitutions:
  _STAGING_PROJECT_ID: null

steps:

- id: &PublishImages Publish Images
  name: gcr.io/cloud-builders/docker
  waitFor:
  - '-'
  entrypoint: bash
  args:
  - -ceux
  - |
    docker pull gcr.io/$_STAGING_PROJECT_ID/metering/ubbagent:sha_$COMMIT_SHA
    docker tag gcr.io/$_STAGING_PROJECT_ID/metering/ubbagent:sha_$COMMIT_SHA gcr.io/$PROJECT_ID/metering/ubbagent:$TAG_NAME

- id: &DetermineShouldTagLatest Determine if images should be tagged latest
  name: gcr.io/cloud-builders/gcloud
  waitFor:
  - *PublishImages
  entrypoint: /bin/bash
  args:
  - -ceux
  - echo "$(.cloudbuild/should_tag_latest.sh gcr.io/$PROJECT_ID/metering/ubbagent $TAG_NAME)" > should_tag_latest

- id: Maybe tag images latest
  name: gcr.io/cloud-builders/docker
  waitFor:
  - *DetermineShouldTagLatest
  entrypoint: /bin/bash
  args:
  - -ceux
  - |
    if [[ "$(cat should_tag_latest)" == "true" ]]; then
      docker tag gcr.io/$PROJECT_ID/metering/ubbagent:$TAG_NAME gcr.io/$PROJECT_ID/metering/ubbagent:latest
      docker push gcr.io/$PROJECT_ID/metering/ubbagent:latest
    else
      echo "Not tagging latest"
    fi

images:
- gcr.io/$PROJECT_ID/metering/ubbagent:$TAG_NAME
