#!/bin/sh
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.FROM golang:1.9.2-alpine3.7 AS build

set -e

if [ -z "$AGENT_CONFIG_FILE" ]; then
  echo "AGENT_CONFIG_FILE environment variable must be set"
  exit 1
fi

if [ -z "$AGENT_STATE_DIR" ]; then
  STATE="--no-state"
else
  STATE="--state-dir=$AGENT_STATE_DIR"
fi

if [ -z "$AGENT_LOCAL_PORT" ]; then
  HTTP="--no-http"
else
  HTTP="--local-port=$AGENT_LOCAL_PORT"
fi

cat "$AGENT_CONFIG_FILE" | envsubst > /tmp/ubbagent-envsubst.yaml
exec ubbagent \
  --config /tmp/ubbagent-envsubst.yaml \
  "$STATE" \
  "$HTTP" \
  --logtostderr --v=2
