// Copyright 2017 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#define Py_LIMITED_API
#include <Python.h>

// PyAgent is our Agent object type. The only state is an agent number which maps back to state
// stored on the Go side.
typedef struct {
    PyObject_HEAD
    int agentnum;
} Agent;

// These declarations must match the exported function definitions generated by api.go.
int AgentInit(Agent *self, PyObject *args, PyObject *kwds);
PyObject *AgentShutdown(Agent *self, PyObject *unused);
PyObject *AgentAddReport(Agent *self, PyObject *report);
PyObject *AgentGetStatus(Agent *self, PyObject *unused);
void AgentDealloc(Agent *self);

// Custom error object used for Agent exceptions.
extern PyObject *AgentError;
